src/Entity/Establishment.php
<?php

namespace App\Entity;

use App\Repository\EstablishmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EstablishmentRepository::class)]
class Establishment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $address;

    #[ORM\Column(type: 'string', length: 100)]
    private $city;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $image;

    #[ORM\OneToMany(mappedBy: 'establishment', targetEntity: Suites::class)]
    private $suites;


    #[ORM\OneToOne(mappedBy: 'establishment', targetEntity: Manager::class, cascade: ['persist', 'remove'])]
    private $manager;

    #[ORM\OneToMany(mappedBy: 'establishment', targetEntity: Booking::class)]
    private $bookings;

    public function __construct()
    {
        $this->suites = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->city.' - '.$this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Suites>
     */
    public function getSuites(): Collection
    {
        return $this->suites;
    }

    public function addSuite(Suites $suite): self
    {
        if (!$this->suites->contains($suite)) {
            $this->suites[] = $suite;
            $suite->setEstablishment($this);
        }

        return $this;
    }

    public function removeSuite(Suites $suite): self
    {
        if ($this->suites->removeElement($suite)) {
            // set the owning side to null (unless already changed)
            if ($suite->getEstablishment() === $this) {
                $suite->setEstablishment(null);
            }
        }

        return $this;
    }

    public function getManager(): ?Manager
    {
        return $this->Manager;
    }

    public function setManager(?Manager $Manager): self
    {
        // unset the owning side of the relation if necessary
        if ($Manager === null && $this->Manager !== null) {
            $this->Manager->setEstablishment(null);
        }

        // set the owning side of the relation if necessary
        if ($Manager !== null && $Manager->getEstablishment() !== $this) {
            $Manager->setEstablishment($this);
        }

        $this->Manager = $Manager;

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setEstablishment($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getEstablishment() === $this) {
                $booking->setEstablishment(null);
            }
        }

        return $this;
    }
}

src/Entity/Suites.php
<?php

namespace App\Entity;

use App\Repository\SuitesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SuitesRepository::class)]
class Suites
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $main_image;

    #[ORM\Column(type: 'integer')]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    private $booking_link;

    #[ORM\ManyToOne(targetEntity: Establishment::class, inversedBy: 'suites')]
    #[ORM\JoinColumn(nullable: false)]
    private $establishment;

    #[ORM\OneToOne(mappedBy: 'suite', targetEntity: Gallery::class, cascade: ['persist', 'remove'])]
    private $gallery;

    public function __toString()
    {
        return $this->name.' - '.$this->price.'€ / la nuit';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMainImage(): ?string
    {
        return $this->main_image;
    }

    public function setMainImage(string $main_image): self
    {
        $this->main_image = $main_image;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getBookingLink(): ?string
    {
        return $this->booking_link;
    }

    public function setBookingLink(string $booking_link): self
    {
        $this->booking_link = $booking_link;

        return $this;
    }

    public function getEstablishment(): ?Establishment
    {
        return $this->establishment;
    }

    public function setEstablishment(?Establishment $establishment): self
    {
        $this->establishment = $establishment;

        return $this;
    }

    public function getGallery(): ?Gallery
    {
        return $this->gallery;
    }

    public function setGallery(Gallery $gallery): self
    {
        // set the owning side of the relation if necessary
        if ($gallery->getSuite() !== $this) {
            $gallery->setSuite($this);
        }

        $this->gallery = $gallery;

        return $this;
    }
}

src/Controller/EstablishmentsController.php
<?php

namespace App\Controller;

use App\Entity\Establishment;
use App\Entity\Suites;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EstablishmentsController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/nos-etablissements', name: 'establishments')]
    public function index(): Response
    {
        $establishments = $this->entityManager->getRepository(Establishment::class)->findAll();

        return $this->render('establishments/index.html.twig', [
            'establishments' => $establishments
        ]);
    }

    #[Route('/nos-etablissements/{id}', name: 'establishment')]
    public function show($id)
    {
        $establishment = $this->entityManager->getRepository(Establishment::class)->findOneById($id);
        $suites = $this->entityManager->getRepository(Suites::class)->findByEstablishments($id);

        if(!$establishment) {
            return $this->redirectToRoute('establishments');
        }

        return $this->render('establishments/one.html.twig', [
            'establishment' => $establishment,
            'suites' => $suites
    ]);
    }
}

templates/establishments/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hypnos Hôtels - Nos Établissements{% endblock %}

{% block content %}
    <div class="container">
        <div class="heading-page text-center">
            <h2> Découvrez nos Établissements</h2>
        </div>

        <section class="establishment-cards">
            <div class="row">
                {% for establishment in establishments %}
                <div class="col-md-6 d-flex flex-column align-items-center">
                    <div class="card">
                        <img class="card-img-top" src="/uploads/{{ establishment.image }}"
                             alt="{{ establishment.name }}">
                        <div class="card-body">
                            <a href="{{ path('establishment', {'id' : establishment.id }) }}">
                            <h3 class="card-title">{{ establishment.city}} - {{ establishment.name }}</h3>
                            <div class="card-text text-start mt-3">{{ establishment.description | raw }}</div>
                            </a>
                        </div>
                    </div>
                </div>

                {% endfor %}
            </div>

        </section>
    </div>

{% endblock %}

templates/establishments/one.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hypnos Hôtels - {{ establishment.city }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="heading-page text-center">
            <h2> Hôtel - {{ establishment.name}} <br> Nos Suites </h2>
        </div>
<div class="row">
    {% for suite in suites %}
    <div class="col">
        <div class="suite-card d-flex flex-column flex-lg-row justify-content-center mb-5">
            <div class="suite-images">
            <img class="mx-auto mainSuiteImage" src="/uploads/{{ suite.mainImage }}" alt="Image de la Suite">
            <div class="gallery d-flex flex-wrap justify-content-md-between justify-content-evenly mt-3">
                {% if suite.gallery %}
                <img src="/uploads/{{ suite.gallery.photo1 }}" alt="photo de la suite"
                     width="120px">
                <img src="/uploads/{{ suite.gallery.photo2 }}" alt="photo de la suite"
                     width="120px">
                <img class="mt-3 mt-md-0" src="/uploads/{{ suite.gallery.photo3 }}" alt="photo de la suite"
                     width="120px">
                {% endif %}
            </div>
            </div>
            <div class="suite-infos ms-lg-5">
                <h3 class="my-4">Suite "{{ suite.name }}"</h3>
                <p>{{ suite.description|raw }} </p>
                <div class="suite-btn">
                <a href="{{ suite.bookingLink }}" class="btn">Voir sur Booking.fr</a>
                <a href="{{ path('oneSuiteBooking', {id : suite.id}) }}" class="btn">Réserver</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
    </div>

{% endblock %}